version: '3'

services:
  master:
    build:
      args:
        LOCUST_VERSION: "2.16.1"
    command: -f /mnt/locust/${LOCUST_FILE} --master
    ports:
     - 8089:8089
    volumes:
      - ${PWD}/locust:/mnt/locust

  worker:
    build:
      args:
        LOCUST_VERSION: "2.16.1"
    command: -f /mnt/locust/${LOCUST_FILE} --worker --master-host master
    volumes:
      - ${PWD}/locust:/mnt/locust

