version: '3'

services:
  master:
    build:
      context: base/apps/locust
      args:
        LOCUST_VERSION: 2.12.2
    command: -f /mnt/locust --master
    ports:
     - 8089:8089
    volumes:
      - ${PWD}/locust:/mnt/locust

  worker:
    build:
      context: base/apps/locust
      args:
        LOCUST_VERSION: 2.12.2
    command: -f /mnt/locust --worker --master-host master
    volumes:
      - ${PWD}/locust:/mnt/locust

