export interface IEnvironment {
  production: boolean,
  name: 'dev' | 'staging' | 'prod',
  storageVersion: number,
  storageKey: string,
  mock: boolean,
  httpMock: boolean,
  httpCache: boolean,
  appUrl: string,
  backendUrl: string,
  backendAppClientKey: string,
  backendAppClientSecret: string,
  authGoogleClientId?: string,
  gtmId?: string,
  fbPixelId?: string,
}
