version: '3.9'

services:

  web:
    build:
      context: ./base/dockerfiles/node
      args:
        NODE_VERSION: 16
        NPM_VERSION: 8
        ANGULAR_VERSION: 14
    command: /bin/sh -c "npm start; tail -f /dev/null"
    ports:
      - ${PORT}01:4200
    volumes:
      - ./credentials/.aws/:/home/node/.aws/
      - ${SRC_WEB}:/home/node/app

  web_dist:
    build:
      context: ./base/dockerfiles/nginx
      args:
        NGINX_VERSION: 1.21.4
    ports:
      - ${PORT}02:80
    volumes:
      - ./base/dockerfiles/nginx/for-html.conf:/etc/nginx/conf.d/default.conf
      - ./credentials/.ssh/:/root/.ssh/
      - ./credentials/.aws/:/root/.aws/
      - ${SRC_WEB}:/var/www/html

  mobile:
    build:
      context: ./base/dockerfiles/node
      args:
        NODE_VERSION: 16
        NPM_VERSION: 7
        ANGULAR_VERSION: 12
        IONIC_VERSION: 6
    command: /bin/sh -c "npm start; tail -f /dev/null;"
    ports:
      - ${PORT}05:8100
    volumes:
      - ${SRC_MOBILE}:/home/node/app

  backoffice:
    build:
      context: ./base/dockerfiles/node
      args:
        NODE_VERSION: 16
        NPM_VERSION: 8
    command: /bin/sh -c "npm start; tail -f /dev/null"
    ports:
      - ${PORT}06:3000
    volumes:
      - ./credentials/.aws/:/home/node/.aws/
      - ${SRC_BACKOFFICE}:/home/node/app

  backend:
    build:
      context: ./base/dockerfiles/nginx
      args:
        NGINX_VERSION: 1.21.4
    links:
      - backend-php:php
    ports:
      - ${PORT}11:80
    volumes:
      - ./base/dockerfiles/nginx/for-php.conf:/etc/nginx/conf.d/default.conf
      - ./credentials/.aws/:/root/.aws/
      - ./credentials/.ssh/:/root/.ssh/
      - ${SRC_BACKEND}:/var/www/html
    networks:
      - default
      # - dp-locust_default

  backend-php:
    build:
      context: ./base/dockerfiles/php
      args:
        PHP_VERSION: 8.1.8-fpm
        COMPOSER_VERSION: --2
    ports:
      - ${PORT}12:8089
    volumes:
      - ./base/dockerfiles/php/php.ini:/usr/local/etc/php/php.ini
      - ./credentials/.aws/:/home/docker/.aws/
      - ./credentials/.ssh/:/home/docker/.ssh/
      - ${SRC_BACKEND}:/var/www/html

  database:
    build:
      context: ./base/dockerfiles/mariadb
      args:
        MARIADB_VERSION: 10.4
    environment:
      MYSQL_USER: ${DB_USER:-admin}
      MYSQL_PASSWORD: ${DB_PASS:-root}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-root}
      MYSQL_DATABASE: ${DB_NAME:-main}
    ports:
      - ${PORT}21:3306
    volumes:
      - ./database-exports/:/home/mysql/exports/
      - database:/var/lib/mysql

  # database:
  #   build:
  #     context: ./base/dockerfiles/postgres
  #     args:
  #       POSTGRES_VERSION: 14.1
  #   environment:
  #     POSTGRES_USER: ${DB_USER:-admin}
  #     POSTGRES_PASSWORD: ${DB_PASS:-root}
  #     POSTGRES_DB: ${DB_NAME:-main}
  #   ports:
  #     - ${PORT}21:5432
  #   volumes:
  #     - ./database-exports/:/home/root/exports/
  #     - database:/var/lib/postgresql/data

volumes:
  database:

networks:
  dp-locust_default:
    external: true
