ARG POSTGRES_VERSION=latest
FROM postgres:${POSTGRES_VERSION}-alpine

WORKDIR /docker/src
COPY bin /docker/bin
ENV PATH="/root/.local/bin:${PATH}"

##############################
##############################
