import { TCountry } from "../types/country.type";

export const getCountryInfo = (countryIso: string | null) => {
  return countriesInfo.find(item => item.iso === countryIso) || countriesInfo.find(item => item.iso === 'US')!;
};

export const countriesInfo: TCountry[] = [
  {
    name: "United States",
    iso: "US",
    phoneRegex: "^\\d{10}$",
    phoneCode: 1,
    maxDigits: 10,
  },
  {
    name: "Argentina",
    iso: "AR",
    phoneRegex: "^(9[0-9]{10})$",
    phoneCode: 54,
    maxDigits: 11,
  },
  {
    name: "Australia",
    iso: "AU",
    phoneRegex: "^([4-5][0-9]{8})$",
    phoneCode: 61,
    maxDigits: 9,
  },
  {
    name: "Austria",
    iso: "AT",
    phoneRegex: "^(6[0-9]{9})$",
    phoneCode: 43,
    maxDigits: 10,
  },
  {
    name: "Belgium",
    iso: "BE",
    phoneRegex: "^(4[0-9]{8})$",
    phoneCode: 32,
    maxDigits: 9,
  },
  {
    name: "Bolivia",
    iso: "BO",
    phoneRegex: "^([6-7][0-9]{7})$",
    phoneCode: 591,
    maxDigits: 8,
  },
  {
    name: "Brazil",
    iso: "BR",
    phoneRegex: "^([1-9][1-9]9[0-9]{7,8})$",
    phoneCode: 55,
    maxDigits: 11,
  },
  {
    name: "Canada",
    iso: "CA",
    phoneRegex: "^([2-9][0-9][0-9][1-9]{7})$",
    phoneCode: 1,
    maxDigits: 10,
  },
  {
    name: "Cayman Islands",
    iso: "KY",
    phoneRegex: "^([2-9][0-9]{9})$",
    phoneCode: 1,
    maxDigits: 10,
  },
  {
    name: "Colombia",
    iso: "CO",
    phoneRegex: "^(3[0-9]{9})$",
    phoneCode: 57,
    maxDigits: 10,
  },
  {
    name: "Costa Rica",
    iso: "CR",
    phoneRegex: "^(8[0-9]{7})$",
    phoneCode: 506,
    maxDigits: 8,
  },
  {
    name: "Cuba",
    iso: "CU",
    phoneRegex: "^([5-6][0-9]{7})$",
    phoneCode: 53,
    maxDigits: 8,
  },
  {
    name: "Czech Republic",
    iso: "CZ",
    phoneRegex: "^([6-7][0-9]{8})$",
    phoneCode: 420,
    maxDigits: 9,
  },
  {
    name: "Denmark",
    iso: "DK",
    phoneRegex: "^([0-9]{8})$",
    phoneCode: 45,
    maxDigits: 8,
  },
  {
    name: "Dominican Republic",
    iso: "DO",
    phoneRegex: "^([2-9][0-9]{9})$",
    phoneCode: 1,
    maxDigits: 10,
  },
  {
    name: "Ecuador",
    iso: "EC",
    phoneRegex: "^(9[0-9]{8})$",
    phoneCode: 593,
    maxDigits: 9,
  },
  {
    name: "El Salvador",
    iso: "SV",
    phoneRegex: "^(7[0-9]{7})$",
    phoneCode: 503,
    maxDigits: 8,
  },
  {
    name: "France",
    iso: "FR",
    phoneRegex: "^([6-7][0-9]{8})$",
    phoneCode: 33,
    maxDigits: 9,
  },
  {
    name: "Germany",
    iso: "DE",
    phoneRegex: "^(1[5,7][0-9]{9})$",
    phoneCode: 49,
    maxDigits: 11,
  },
  {
    name: "Greece",
    iso: "GR",
    phoneRegex: "^(6[0-9]{9})$",
    phoneCode: 30,
    maxDigits: 10,
  },
  {
    name: "Guatemala",
    iso: "GT",
    phoneRegex: "^([3-5][0-9]{7})$",
    phoneCode: 502,
    maxDigits: 8,
  },
  {
    name: "Guyana",
    iso: "GY",
    phoneRegex: "^(6[0-9]{6})$",
    phoneCode: 592,
    maxDigits: 7,
  },
  {
    name: "Honduras",
    iso: "HN",
    phoneRegex: "^([3,8-9][0-9]{7})$",
    phoneCode: 504,
    maxDigits: 8,
  },
  {
    name: "Hungary",
    iso: "HU",
    phoneRegex: "^(20|30|31|50|70)([0-9]{7})$",
    phoneCode: 36,
    maxDigits: 9,
  },
  {
    name: "Israel",
    iso: "IL",
    phoneRegex: "^(5[0-9]{8})$",
    phoneCode: 972,
    maxDigits: 9,
  },
  {
    name: "Italy",
    iso: "IT",
    phoneRegex: "^(3[0-9]{9})$",
    phoneCode: 39,
    maxDigits: 10,
  },
  {
    name: "Jamaica",
    iso: "JM",
    phoneRegex: "^([2-9][0-9]{9})$",
    phoneCode: 1,
    maxDigits: 10,
  },
  {
    name: "Mexico",
    iso: "MX",
    phoneRegex: "^([2-9][0-9]{9})$",
    phoneCode: 52,
    maxDigits: 10,
  },
  {
    name: "Netherlands",
    iso: "NL",
    phoneRegex: "^(6[0-9]{8})$",
    phoneCode: 31,
    maxDigits: 9,
  },
  {
    name: "Nicaragua",
    iso: "NI",
    phoneRegex: "^(8[0-9]{7})$",
    phoneCode: 505,
    maxDigits: 8,
  },
  {
    name: "Panama",
    iso: "PA",
    phoneRegex: "^(6[0-9]{7})$",
    phoneCode: 507,
    maxDigits: 8,
  },
  {
    name: "Peru",
    iso: "PE",
    phoneRegex: "^(9[0-9]{8})$",
    phoneCode: 51,
    maxDigits: 9,
  },
  {
    name: "Portugal",
    iso: "PT",
    phoneRegex: "^(9[0-9]{8})$",
    phoneCode: 351,
    maxDigits: 9,
  },
  {
    name: "Qatar",
    iso: "QA",
    phoneRegex: "^([3,5-7][0-9]{7})$",
    phoneCode: 974,
    maxDigits: 8,
  },
  {
    name: "Russia",
    iso: "RU",
    phoneRegex: "^(9[0-9]{9})$",
    phoneCode: 7,
    maxDigits: 10,
  },
  {
    name: "Saudi Arabia",
    iso: "SA",
    phoneRegex: "^(5[0-9]{8})$",
    phoneCode: 966,
    maxDigits: 9,
  },
  {
    name: "Singapore",
    iso: "SG",
    phoneRegex: "^([8-9][0-9]{7})$",
    phoneCode: 65,
    maxDigits: 8,
  },
  {
    name: "Spain",
    iso: "ES",
    phoneRegex: "^([6-7][0-9]{8})$",
    phoneCode: 34,
    maxDigits: 9,
  },
  {
    name: "Suriname",
    iso: "SR",
    phoneRegex: "^([7-8][0-9]{6})$",
    phoneCode: 597,
    maxDigits: 7,
  },
  {
    name: "Sweden",
    iso: "SE",
    phoneRegex: "^(7[0-9]{8})$",
    phoneCode: 46,
    maxDigits: 9,
  },
  {
    name: "Switzerland",
    iso: "CH",
    phoneRegex: "^(7[0-9]{8})$",
    phoneCode: 41,
    maxDigits: 9,
  },
  {
    name: "Trinidad and Tobago",
    iso: "TT",
    phoneRegex: "^([2-9][0-9]{9})$",
    phoneCode: 1,
    maxDigits: 10,
  },
  {
    name: "Turks and Caicos Islands",
    iso: "TC",
    phoneRegex: "^([2-9][0-9]{9})$",
    phoneCode: 1,
    maxDigits: 10,
  },
  {
    name: "United Arab Emirates",
    iso: "AE",
    phoneRegex: "^(5[0-9]{8})$",
    phoneCode: 971,
    maxDigits: 9,
  },
  {
    name: "United Kingdom",
    iso: "GB",
    phoneRegex: "^(7[0-9]{9})$",
    phoneCode: 44,
    maxDigits: 10,
  },
  {
    name: "Uruguay",
    iso: "UY",
    phoneRegex: "^(9[0-9]{7})$",
    phoneCode: 598,
    maxDigits: 8,
  },
  {
    name: "Venezuela",
    iso: "VE",
    phoneRegex: "^(4[0-9]{9})$",
    phoneCode: 58,
    maxDigits: 10,
  }
];
